
$(document).ready(function(){
    $(".kuo0").show();
    $("#01izquierda").hide();
    $(".kuo1").hide();
    $(".kuo2").hide();
    var i4=0;
    var d4=false;

    $("#equipment").on("click",function(){
        $(".kuo0").show();
        $("#00izquierda").show();
        $(".containerAños").hide();
        $(".kuo1").hide(1000);
        $(".kuo2").hide(1000);
        d4 = true;
    });
    $("#kuoToday").on("click",function(){
        $(".kuo0").hide(1000);
        $(".kuo1").show();
        $(".kuo2").hide(1000);
        $("#01izquierda").show();
       
        d4 = true;
    });
    $("#business").on("click",function(){
        $(".kuo0").hide(1000);
        $(".kuo1").hide(1000);
        $(".kuo2").show(1000);
        $("#kuo01img").hide();
        $("#kuo02img").hide();
        $("#kuo03img").hide();
        $("#kuo04img").hide();
        $("#kuo05img").hide();
        $("#kuo06img").hide();
        $("#kuo07img").hide();
        $("#kuo08img").hide();
        $("#kuo09img").hide();
        d4 = true;
    });
    $("#back").on("click",function(){
        $("#00izquierda").show();
        $("#00derecha").show();
        $(".containerAños").hide();
        $(".tremec1").hide(1000);
        $(".tremec2").hide(1000);
    });

    $("#paisesKUO").on("click",function(){
        $("#mapa").show();
    });
    $(".sinpaisesKUO").on("click",function(){
        $("#mapa").hide();
    });


    $("#p1973").on("click",function(){
       
        $(".containerAños").show();
        $("#img1973").show();
        $("#img1980").hide();
        $("#img1988").hide();
        $("#img1997").hide();
        $("#img2007").hide();
        $("#img2008").hide();
        $("#img2009").hide();
        $("#img2010").hide();
        $("#img2011").hide();
        $("#img2013").hide();
        $("#img2015").hide();
        $("#img2018").hide();
    });
    $("#p2018").on("click",function(){
      
       
        $(".containerAños").show();
        $("#img1973").hide();
        $("#img1980").hide();
        $("#img1988").hide();
        $("#img1997").hide();
        $("#img2007").hide();
        $("#img2008").hide();
        $("#img2009").hide();
        $("#img2010").hide();
        $("#img2011").hide();
        $("#img2013").hide();
        $("#img2015").hide();
        $("#img2018").show();
    });
    $("#p1980").on("click",function(){
       
      
        $(".containerAños").show();
        $("#img1973").hide();
        $("#img1980").show();
        $("#img1988").hide();
        $("#img1997").hide();
        $("#img2007").hide();
        $("#img2008").hide();
        $("#img2009").hide();
        $("#img2010").hide();
        $("#img2011").hide();
        $("#img2013").hide();
        $("#img2015").hide();
        $("#img2018").hide();
    });
    $("#p1988").on("click",function(){

        $(".containerAños").show();
        $("#img1973").hide();
        $("#img1980").hide();
        $("#img1988").show();
        $("#img1997").hide();
        $("#img2007").hide();
        $("#img2008").hide();
        $("#img2009").hide();
        $("#img2010").hide();
        $("#img2011").hide();
        $("#img2013").hide();
        $("#img2015").hide();
        $("#img2018").hide();
    });
    $("#p1997").on("click",function(){
      
        $(".containerAños").show();
        $("#img1973").hide();
        $("#img1980").hide();
        $("#img1988").hide();
        $("#img1997").show();
        $("#img2007").hide();
        $("#img2008").hide();
        $("#img2009").hide();
        $("#img2010").hide();
        $("#img2011").hide();
        $("#img2013").hide();
        $("#img2015").hide();
        $("#img2018").hide();
    });
    $("#p2007").on("click",function(){
 
 
        $(".containerAños").show();
        $("#img1973").hide();
        $("#img1980").hide();
        $("#img1988").hide();
        $("#img1997").hide();
        $("#img2007").show();
        $("#img2008").hide();
        $("#img2009").hide();
        $("#img2010").hide();
        $("#img2011").hide();
        $("#img2013").hide();
        $("#img2015").hide();
        $("#img2018").hide();
    });
    $("#p2008").on("click",function(){
        console.log("ho");

        $(".containerAños").show();
        $("#img1973").hide();
        $("#img1980").hide();
        $("#img1988").hide();
        $("#img1997").hide();
        $("#img2007").hide();
        $("#img2008").show();
        $("#img2009").hide();
        $("#img2010").hide();
        $("#img2011").hide();
        $("#img2013").hide();
        $("#img2015").hide();
        $("#img2018").hide();
    });
    $("#p2009").on("click",function(){


        $(".containerAños").show();
        $("#img1973").hide();
        $("#img1980").hide();
        $("#img1988").hide();
        $("#img1997").hide();
        $("#img2007").hide();
        $("#img2008").hide();
        $("#img2009").show();
        $("#img2010").hide();
        $("#img2011").hide();
        $("#img2013").hide();
        $("#img2015").hide();
        $("#img2018").hide();
    });
    $("#p2010").on("click",function(){

        $(".containerAños").show();
        $("#img1973").hide();
        $("#img1980").hide();
        $("#img1988").hide();
        $("#img1997").hide();
        $("#img2007").hide();
        $("#img2008").hide();
        $("#img2009").hide();
        $("#img2010").show();
        $("#img2011").hide();
        $("#img2013").hide();
        $("#img2015").hide();
        $("#img2018").hide();
    });
    $("#p2011").on("click",function(){
        console.log("ho");

        $(".containerAños").show();
        $("#img1973").hide();
        $("#img1980").hide();
        $("#img1988").hide();
        $("#img1997").hide();
        $("#img2007").hide();
        $("#img2008").hide();
        $("#img2009").hide();
        $("#img2010").hide();
        $("#img2011").show();
        $("#img2013").hide();
        $("#img2015").hide();
        $("#img2018").hide();
    });
    $("#p2013").on("click",function(){
        console.log("ho");

        $(".containerAños").show();
        $("#img1973").hide();
        $("#img1980").hide();
        $("#img1988").hide();
        $("#img1997").hide();
        $("#img2007").hide();
        $("#img2008").hide();
        $("#img2009").hide();
        $("#img2010").hide();
        $("#img2011").hide();
        $("#img2013").show();
        $("#img2015").hide();
        $("#img2018").hide();
    });
    $("#p2015").on("click",function(){
        console.log("ho");

        $(".containerAños").show();
        $("#img1973").hide();
        $("#img1980").hide();
        $("#img1988").hide();
        $("#img1997").hide();
        $("#img2007").hide();
        $("#img2008").hide();
        $("#img2009").hide();
        $("#img2010").hide();
        $("#img2011").hide();
        $("#img2013").hide();
        $("#img2015").show();
        $("#img2018").hide();
    });
    $("#kuo01").on("click",function(){
        $("#kuo01img").show();
        $("#kuo02img").hide();
        $("#kuo03img").hide();
        $("#kuo04img").hide();
        $("#kuo05img").hide();
        $("#kuo06img").hide();
        $("#kuo07img").hide();
        $("#kuo08img").hide();
        $("#kuo09img").hide();
    });
    $("#kuo02").on("click",function(){
        $("#kuo01img").hide();
        $("#kuo02img").show();
        $("#kuo03img").hide();
        $("#kuo04img").hide();
        $("#kuo05img").hide();
        $("#kuo06img").hide();
        $("#kuo07img").hide();
        $("#kuo08img").hide();
        $("#kuo09img").hide();
    });
    $("#kuo03").on("click",function(){
        $("#kuo01img").hide();
        $("#kuo02img").hide();
        $("#kuo03img").show();
        $("#kuo04img").hide();
        $("#kuo05img").hide();
        $("#kuo06img").hide();
        $("#kuo07img").hide();
        $("#kuo08img").hide();
        $("#kuo09img").hide();
    });
    $("#kuo04").on("click",function(){
        $("#kuo01img").hide();
        $("#kuo02img").hide();
        $("#kuo03img").hide();
        $("#kuo04img").show();
        $("#kuo05img").hide();
        $("#kuo06img").hide();
        $("#kuo07img").hide();
        $("#kuo08img").hide();
        $("#kuo09img").hide();
    });
    $("#kuo05").on("click",function(){
        $("#kuo01img").hide();
        $("#kuo02img").hide();
        $("#kuo03img").hide();
        $("#kuo04img").hide();
        $("#kuo05img").show();
        $("#kuo06img").hide();
        $("#kuo07img").hide();
        $("#kuo08img").hide();
        $("#kuo09img").hide();
    });
    $("#kuo06").on("click",function(){
        $("#kuo01img").hide();
        $("#kuo02img").hide();
        $("#kuo03img").hide();
        $("#kuo04img").hide();
        $("#kuo05img").hide();
        $("#kuo06img").show();
        $("#kuo07img").show();
        $("#kuo08img").show();
        $("#kuo09img").show();
    });
    $("#kuo07").on("click",function(){
        $("#kuo01img").hide();
        $("#kuo02img").hide();
        $("#kuo03img").hide();
        $("#kuo04img").hide();
        $("#kuo05img").hide();
        $("#kuo06img").hide();
        $("#kuo07img").show();
        $("#kuo08img").hide();
        $("#kuo09img").hide();
    });
    $("#kuo08").on("click",function(){
        $("#kuo01img").hide();
        $("#kuo02img").hide();
        $("#kuo03img").hide();
        $("#kuo04img").hide();
        $("#kuo05img").hide();
        $("#kuo06img").hide();
        $("#kuo07img").hide();
        $("#kuo08img").show();
        $("#kuo09img").hide();
    });
    $("#kuo09").on("click",function(){
        $("#kuo01img").hide();
        $("#kuo02img").hide();
        $("#kuo03img").hide();
        $("#kuo04img").hide();
        $("#kuo05img").hide();
        $("#kuo06img").hide();
        $("#kuo07img").hide();
        $("#kuo08img").hide();
        $("#kuo09img").show();
    });
    $("#back").on("click",function(){
        
        $(".kuo0").show(1000);
        $(".kuo1").hide(1000);
        $(".kuo2").hide(1000);
     
 });
});




//cargar la 1er imagen

